Mensagens:

  Gamemode:
    Utilize: "&cUtilize: /gamemode (0, 1, 2, 3) (jogador)"
    JogadorNaoEncontrado: "&cEste jogador não foi encontrado."
    Invalido: "&cO modo de jogo &7'{gamemode}' &cé inválido."
    JaEstaOutro: "&cO jogador &7{player} &cjá está no modo de jogo &7{gamemode}&c."
    AlteradoOutro: "&eModo de jogo &7{gamemode} &edefinido com sucesso para &7{player}&e."
    JaEsta: "&cVocê já está no modo de jogo &7{gamemode}&c."
    Alterado: "&eModo de jogo alterado com sucesso para &7{gamemode}&e."
    Log: "&7[{player} alterou o seu modo de jogo para {gamemode}]"
    LogOutros: "&7[{player} alterou o modo de jogo de {player2} para {gamemode}]"
    SemPermissaoOutros: "&cVocê não tem permissão para alterar o modo de jogo de outros jogadores."
    SemPermissaoEspecifico: "&cVocê não tem permissão para alterar o seu modo de jogo para &7{gamemode}&c."
    SemPermissao: "&cComando não encontrado."

    Permissions:
      permission specific: "voxygamemode.gamemode."
      permission other: "voxygamemode.use.other"
      permission: "voxygamemode.use"
      permission-log: "voxygamemode.gamemode.log"

  Utils:
    Desativar chuva: true
    Sistema de Comandos: false
    Comandos liberados: ["/login", "/logar"]
