#Está é a configuração principal, onde poderá habilitar ou desabilitar algum sistema do plugin.
#True = sistema habilitado, false = sistema desabilitado.

commons:
  profileranimations: true
  curas: true
  uteis: true
  essentials: true
  modo staff: true

#Sistema de reload desabilitado, ignore a configuração abaixo.
Mensagens:
  Comando: "Comando não encontrado."
  Reload: "&cO plugin foi recarregado com sucesso!"
  Ajuda:
    - ""
    - "&eCommons Commands"
    - ""
    - "/commons reload"
    - ""
